FROM mysql:5.7

# RUN apt-get update && \
#     apt-get install -y iptables && \
#     rm -rf /var/lib/apt/lists/*
RUN yum install -y iptables && yum install -y netcat && yum clean all
COPY entrypoint-mysql.sh /usr/local/bin/entrypoint-mysql.sh
RUN chmod +x /usr/local/bin/entrypoint-mysql.sh

ENTRYPOINT ["entrypoint-mysql.sh"]
